name: Build And Deploy To Kind

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Environment
        run: |
          java -version
          mvn -v
          docker --version
          kubectl version --client
          kind version

      - name: Build Jar
        run: |
          mvn clean package -DskipTests

      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
            -t myapp:${IMAGE_TAG} \
            -f Dockerfile-simple .

      - name: Load Image Into Kind
        run: |
          kind load docker-image myapp:${IMAGE_TAG}

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/user-service \
            user-service=myapp:${IMAGE_TAG}

      - name: Wait Rollout
        run: |
          kubectl rollout status deployment/user-service --timeout=300s

      - name: Show Pods
        run: |
          kubectl get pods -o wide

      - name: Show Service
        run: |
          kubectl get svc