name: Restart Deployment

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Build Jar
        run: |
          mvn clean package -DskipTests

      - name: Build Image
        run: |
          docker build -t myapp:dev .

      - name: Load Image
        run: |
          kind load docker-image myapp:dev

      - name: Restart
        run: |
          kubectl rollout restart deployment/user-service

      - name: Wait
        run: |
          kubectl rollout status deployment/user-service